### ISSUE TITLE
C++: Spiral print a 2-D array

### ISSUE THREAD

**Issue by SonaVarshney** [adarshpand3y/Hacktoberfest2022-DSA-excluded-2#364]
@adarshpand3y please assign me this issue

**Comment by SayuruRehan** [comment]
is anyone assigned to this??

**Comment by iisha27** [comment]
hey, please assign this to me.

**Comment by Amandeep603** [comment]
pls assign this issue to me

**Comment by bhavya-sharma26** [comment]
Can you please assign this issue to me as this is my first open source contribution through participating in Hacktoberfest. And this would be great start for me if you will assign this task to me.

**Comment by Arkapro1** [comment]
After reading the guidelines .. i want to contribute plz assign me the task ;

**Comment by PD2408** [comment]
Can you please assign this issue to me?

**Comment by Ishita2407** [comment]
Please assign this issue to me

**Comment by Harshdeep-codes** [comment]
Hello I am currently preparing DSA this task would be good or me I can write the code for this problem with better time complexity. Thank you!!
