### ISSUE TITLE
Kth Largest Element in an Array

### ISSUE THREAD

**Issue by aishwaryas15** [adarshpand3y/Hacktoberfest2022-DSA-excluded-2#419]
I want to add code for Kth Largest Element in an Array. Please assign me this issue under hacktober fest 2022

**Comment by rajarshigit14** [comment]
Hi, please assign me this issue under Hacktoberfest2022 .

**Comment by jatin1603** [comment]
Hi, can i solve  this issue under Hacktoberfest2022 .

**Comment by inbuilt-aura** [comment]
Hello, if you don't mind i would love to solve your issue easily under hacktoberfest 2022.
