### ISSUE TITLE
Add Patterns in C++ Programming Languages

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [adarshpand3y/Hacktoberfest2022-DSA-excluded-2#537]
I want to add new Patterns in C++

Ex. 
(i) Numerical Spriral Pattern
  1  2  3  4 5
 16 17 18 19 6
 15 24 25 20 7
 14 23 22 21 8
 13 12 11 10 9

(ii) Swastik Pattern
```
*     * * * * 
*     *       
*     *       
* * * * * * *
      *     * 
      *     * 
* * * *     *
```
and many more.

**Comment by Avdhesh-Varshney** [comment]
Please Assign it to me.
I want to work on it.

**Comment by Tanmaybhujade** [comment]
assign it to me
